-- Vehix core schema: per-user vehicles, repairs, trips and compliance documents.
-- Money/distance use double precision (not numeric) so PostgREST returns JSON numbers
-- rather than strings, matching the previous SQLite REAL behaviour.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  brand text not null,
  model text not null,
  year integer not null,
  description text,
  mileage_km double precision,
  photo_path text,
  created_at timestamptz not null default now(),
  -- lets child tables use a composite FK so a row can never point at another user's car
  unique (id, user_id)
);

create table if not exists public.repairs (
  id bigint generated by default as identity primary key,
  car_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  status text not null default 'done' check (status in ('done', 'scheduled')),
  currency text not null default 'RON' check (currency in ('RON', 'EUR')),
  notification_ids text[] not null default '{}',
  mileage_km double precision,
  title text not null,
  date date not null,
  price double precision not null default 0,
  notes text,
  created_at timestamptz not null default now(),
  foreign key (car_id, user_id) references public.cars (id, user_id) on delete cascade
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  car_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  status text not null default 'done' check (status in ('done', 'scheduled')),
  currency text not null default 'RON' check (currency in ('RON', 'EUR')),
  notification_ids text[] not null default '{}',
  date date not null,
  distance double precision not null,
  fuel_used double precision not null,
  gas_price double precision,
  -- derived in the database so the trip cost / consumption maths lives in one place
  price double precision generated always as (
    case when gas_price is null then null else fuel_used * gas_price end
  ) stored,
  consumption double precision generated always as (
    case when distance > 0 then (fuel_used / distance) * 100 else 0 end
  ) stored,
  created_at timestamptz not null default now(),
  foreign key (car_id, user_id) references public.cars (id, user_id) on delete cascade
);

create table if not exists public.compliance_records (
  id bigint generated by default as identity primary key,
  car_id bigint not null,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  kind text not null check (kind in ('itp', 'rca')),
  issued_date date not null,
  expires_date date not null,
  attachment_path text,
  attachment_name text,
  attachment_type text,
  notification_ids text[] not null default '{}',
  created_at timestamptz not null default now(),
  unique (car_id, kind),
  foreign key (car_id, user_id) references public.cars (id, user_id) on delete cascade
);

create index if not exists cars_user_id_created_at_idx on public.cars (user_id, created_at desc, id desc);
create index if not exists repairs_car_id_date_idx on public.repairs (car_id, date desc, id desc);
create index if not exists repairs_user_status_date_idx on public.repairs (user_id, status, date asc, id asc);
create index if not exists repairs_user_spend_idx on public.repairs (user_id, status, currency, date);
create index if not exists trips_car_id_date_idx on public.trips (car_id, date desc, id desc);
create index if not exists trips_user_status_date_idx on public.trips (user_id, status, date asc, id asc);
create index if not exists trips_user_spend_idx on public.trips (user_id, status, currency, date);
create index if not exists compliance_records_car_id_idx on public.compliance_records (car_id, expires_date asc, id desc);
create index if not exists compliance_records_user_id_idx on public.compliance_records (user_id);
