begin;

create table public.drivers (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  phone text,
  email text,
  license_number text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id)
);

create table public.driver_assignments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  driver_id bigint not null,
  car_id bigint,
  vehicle_label text not null,
  starts_on date not null,
  ends_on date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_assignments_dates_check check (ends_on is null or ends_on >= starts_on),
  constraint driver_assignments_driver_fkey foreign key (driver_id, user_id)
    references public.drivers(id, user_id) on delete cascade,
  constraint driver_assignments_car_fkey foreign key (car_id)
    references public.cars(id) on delete set null
);

create table public.weekly_settlements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  driver_id bigint not null,
  car_id bigint,
  vehicle_label text,
  week_start date not null,
  due_date date not null,
  currency text not null default 'RON' check (currency in ('RON', 'EUR')),
  bolt_earnings double precision not null default 0 check (bolt_earnings >= 0),
  uber_earnings double precision not null default 0 check (uber_earnings >= 0),
  fleet_commission double precision not null default 0 check (fleet_commission >= 0),
  vehicle_rent double precision not null default 0 check (vehicle_rent >= 0),
  expenses double precision not null default 0 check (expenses >= 0),
  fines double precision not null default 0 check (fines >= 0),
  bonuses double precision not null default 0 check (bonuses >= 0),
  manual_adjustment double precision not null default 0,
  amount_settled double precision not null default 0 check (amount_settled >= 0),
  notes text,
  gross_earnings double precision generated always as (bolt_earnings + uber_earnings) stored,
  net_amount double precision generated always as (
    bolt_earnings + uber_earnings + bonuses + manual_adjustment
    - fleet_commission - vehicle_rent - expenses - fines
  ) stored,
  outstanding_amount double precision generated always as (
    case
      when bolt_earnings + uber_earnings + bonuses + manual_adjustment
        - fleet_commission - vehicle_rent - expenses - fines >= 0
      then greatest(
        bolt_earnings + uber_earnings + bonuses + manual_adjustment
        - fleet_commission - vehicle_rent - expenses - fines - amount_settled,
        0
      )
      else least(
        bolt_earnings + uber_earnings + bonuses + manual_adjustment
        - fleet_commission - vehicle_rent - expenses - fines + amount_settled,
        0
      )
    end
  ) stored,
  status text generated always as (
    case
      when abs(
        bolt_earnings + uber_earnings + bonuses + manual_adjustment
        - fleet_commission - vehicle_rent - expenses - fines
      ) <= 0.005
        or amount_settled >= abs(
          bolt_earnings + uber_earnings + bonuses + manual_adjustment
          - fleet_commission - vehicle_rent - expenses - fines
        ) - 0.005
      then 'paid'
      when amount_settled > 0.005 then 'partial'
      else 'unpaid'
    end
  ) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint weekly_settlements_week_monday_check check (extract(isodow from week_start) = 1),
  constraint weekly_settlements_due_date_check check (due_date >= week_start),
  constraint weekly_settlements_driver_fkey foreign key (driver_id, user_id)
    references public.drivers(id, user_id) on delete cascade,
  constraint weekly_settlements_car_fkey foreign key (car_id)
    references public.cars(id) on delete set null,
  unique (user_id, driver_id, week_start)
);

create index driver_assignments_user_driver_idx
  on public.driver_assignments (user_id, driver_id, starts_on desc);
create index driver_assignments_user_car_idx
  on public.driver_assignments (user_id, car_id, starts_on desc);
create index driver_assignments_car_id_idx
  on public.driver_assignments (car_id) where car_id is not null;
create index drivers_user_id_idx
  on public.drivers (user_id);
create index weekly_settlements_user_week_idx
  on public.weekly_settlements (user_id, week_start desc);
create index weekly_settlements_user_driver_idx
  on public.weekly_settlements (user_id, driver_id, week_start desc);
create index weekly_settlements_user_status_idx
  on public.weekly_settlements (user_id, status, due_date);
create index weekly_settlements_car_id_idx
  on public.weekly_settlements (car_id) where car_id is not null;

create or replace function public.set_vehix_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.validate_vehix_car_owner()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.car_id is not null and not exists (
    select 1 from public.cars where id = new.car_id and user_id = new.user_id
  ) then
    raise exception 'Vehicle does not belong to this account';
  end if;
  return new;
end;
$$;

create trigger drivers_set_updated_at
before update on public.drivers
for each row execute function public.set_vehix_updated_at();
create trigger driver_assignments_set_updated_at
before update on public.driver_assignments
for each row execute function public.set_vehix_updated_at();
create trigger weekly_settlements_set_updated_at
before update on public.weekly_settlements
for each row execute function public.set_vehix_updated_at();
create trigger driver_assignments_validate_car_owner
before insert or update of car_id, user_id on public.driver_assignments
for each row execute function public.validate_vehix_car_owner();
create trigger weekly_settlements_validate_car_owner
before insert or update of car_id, user_id on public.weekly_settlements
for each row execute function public.validate_vehix_car_owner();

revoke all on function public.set_vehix_updated_at() from public, anon, authenticated;
revoke all on function public.validate_vehix_car_owner() from public, anon, authenticated;

create or replace function public.assign_driver(
  p_driver_id bigint,
  p_car_id bigint,
  p_starts_on date,
  p_notes text default null
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_vehicle_label text;
  v_assignment_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication required'; end if;

  select concat_ws(' ', brand, model, concat('(', year, ')'))
  into v_vehicle_label
  from public.cars
  where id = p_car_id and user_id = v_user_id;

  if v_vehicle_label is null then raise exception 'Vehicle not found'; end if;
  if not exists (select 1 from public.drivers where id = p_driver_id and user_id = v_user_id) then
    raise exception 'Driver not found';
  end if;

  update public.driver_assignments
  set ends_on = greatest(starts_on, p_starts_on - 1)
  where user_id = v_user_id
    and ends_on is null
    and (driver_id = p_driver_id or car_id = p_car_id);

  insert into public.driver_assignments (
    user_id, driver_id, car_id, vehicle_label, starts_on, notes
  ) values (
    v_user_id, p_driver_id, p_car_id, v_vehicle_label, p_starts_on, nullif(trim(p_notes), '')
  ) returning id into v_assignment_id;

  return v_assignment_id;
end;
$$;

revoke all on function public.assign_driver(bigint, bigint, date, text) from public;
grant execute on function public.assign_driver(bigint, bigint, date, text) to authenticated;

alter table public.drivers enable row level security;
alter table public.driver_assignments enable row level security;
alter table public.weekly_settlements enable row level security;

create policy drivers_select_own on public.drivers for select to authenticated
  using ((select auth.uid()) = user_id);
create policy drivers_insert_own on public.drivers for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy drivers_update_own on public.drivers for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy drivers_delete_own on public.drivers for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy driver_assignments_select_own on public.driver_assignments for select to authenticated
  using ((select auth.uid()) = user_id);
create policy driver_assignments_insert_own on public.driver_assignments for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy driver_assignments_update_own on public.driver_assignments for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy driver_assignments_delete_own on public.driver_assignments for delete to authenticated
  using ((select auth.uid()) = user_id);

create policy weekly_settlements_select_own on public.weekly_settlements for select to authenticated
  using ((select auth.uid()) = user_id);
create policy weekly_settlements_insert_own on public.weekly_settlements for insert to authenticated
  with check ((select auth.uid()) = user_id);
create policy weekly_settlements_update_own on public.weekly_settlements for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy weekly_settlements_delete_own on public.weekly_settlements for delete to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.drivers, public.driver_assignments, public.weekly_settlements from anon;
grant select, insert, update, delete on public.drivers, public.driver_assignments, public.weekly_settlements to authenticated;
grant usage, select on sequence public.drivers_id_seq to authenticated;
grant usage, select on sequence public.driver_assignments_id_seq to authenticated;
grant usage, select on sequence public.weekly_settlements_id_seq to authenticated;

commit;
