-- Fleet automation: vehicle identity, full ride-sharing document set, driver documents,
-- fines attributed to drivers, km-based service plans and fuel consumption baselines.

-- Vehicles: plate/VIN identify a car in fines and platform exports; usage decides which documents apply.
alter table public.cars
  add column plate_number text check (plate_number is null or char_length(plate_number) between 2 and 16),
  add column vin text check (vin is null or vin ~ '^[A-HJ-NPR-Z0-9]{17}$'),
  add column fuel_type text check (fuel_type in ('petrol', 'diesel', 'hybrid', 'plugin_hybrid', 'electric', 'lpg')),
  add column euro_class smallint check (euro_class between 0 and 6),
  add column ridesharing boolean not null default false,
  add column mileage_updated_on date not null default current_date;
create unique index cars_user_plate_key on public.cars (user_id, upper(replace(plate_number, ' ', ''))) where plate_number is not null;

-- When the odometer was last read, so service plans can project today's mileage from the driving rate.
create or replace function private.touch_mileage_updated_on()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.mileage_km is distinct from old.mileage_km then
    new.mileage_updated_on := current_date;
  end if;
  return new;
end;
$$;
create trigger cars_touch_mileage_updated_on
  before update of mileage_km on public.cars
  for each row execute function private.touch_mileage_updated_on();

-- Vehicle documents: ride-sharing cars also need passenger insurance, the ARR certified copy and the platform badge.
alter table public.compliance_records drop constraint compliance_records_kind_check;
alter table public.compliance_records add constraint compliance_records_kind_check
  check (kind in ('itp', 'rca', 'vignette', 'passenger_insurance', 'arr_copy', 'badge', 'casco'));

-- Drivers: default weekly terms used when settlements are imported, and the names platforms use for them.
alter table public.drivers
  add column weekly_rent double precision check (weekly_rent >= 0),
  add column commission_rate double precision check (commission_rate between 0 and 100),
  add column platform_names text[] not null default '{}';

create table public.driver_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  driver_id bigint not null,
  kind text not null check (kind in ('license', 'arr_certificate', 'medical', 'psychological', 'criminal_record')),
  issued_date date not null,
  expires_date date not null,
  attachment_path text,
  attachment_name text,
  attachment_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint driver_documents_dates_check check (expires_date >= issued_date),
  constraint driver_documents_driver_fkey foreign key (driver_id, user_id)
    references public.drivers (id, user_id) on delete cascade
);
create index driver_documents_user_idx on public.driver_documents (user_id, expires_date);
create index driver_documents_driver_idx on public.driver_documents (driver_id, user_id);
create trigger driver_documents_set_updated_at
  before update on public.driver_documents
  for each row execute function public.set_vehix_updated_at();

-- Km/time service intervals per vehicle.
create table public.service_plans (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  car_id bigint not null references public.cars (id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 120),
  interval_km integer check (interval_km > 0),
  interval_months integer check (interval_months > 0),
  last_done_on date,
  last_done_km double precision check (last_done_km >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint service_plans_interval_check check (interval_km is not null or interval_months is not null)
);
create index service_plans_user_idx on public.service_plans (user_id);
create index service_plans_car_idx on public.service_plans (car_id);
create trigger service_plans_set_updated_at
  before update on public.service_plans
  for each row execute function public.set_vehix_updated_at();
create trigger service_plans_validate_car_owner
  before insert or update of car_id, user_id on public.service_plans
  for each row execute function public.validate_vehix_car_owner();
create trigger service_plans_block_locked_vehicle
  before insert or update on public.service_plans
  for each row execute function private.block_locked_vehicle_children();

-- Logs a plan as done: one transaction adds the repair, moves the plan forward and raises the odometer.
create or replace function public.complete_service(
  p_plan_id bigint, p_date date, p_mileage_km double precision, p_price double precision, p_currency text, p_notes text default null
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_plan public.service_plans;
  v_repair_id bigint;
begin
  select * into v_plan from public.service_plans where id = p_plan_id;
  if not found then raise exception 'Service plan not found'; end if;
  if p_date > current_date then raise exception 'Completed entries cannot be in the future.'; end if;

  insert into public.repairs (user_id, car_id, status, currency, notification_ids, mileage_km, title, date, price, notes)
  values (v_plan.user_id, v_plan.car_id, 'done', p_currency, '{}', p_mileage_km, v_plan.title, p_date, coalesce(p_price, 0), nullif(trim(p_notes), ''))
  returning id into v_repair_id;

  update public.service_plans
  set last_done_on = p_date, last_done_km = coalesce(p_mileage_km, last_done_km)
  where id = p_plan_id;

  if p_mileage_km is not null then
    update public.cars set mileage_km = p_mileage_km
    where id = v_plan.car_id and (mileage_km is null or mileage_km < p_mileage_km);
  end if;
  return v_repair_id;
end;
$$;
revoke all on function public.complete_service(bigint, date, double precision, double precision, text, text) from public, anon;
grant execute on function public.complete_service(bigint, date, double precision, double precision, text, text) to authenticated;

-- Fines: who had the car decides who pays; settlement_id is set once the fine is deducted in a weekly settlement.
create table public.fines (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  car_id bigint not null references public.cars (id) on delete cascade,
  driver_id bigint references public.drivers (id) on delete set null,
  kind text not null default 'camera' check (kind in ('camera', 'police', 'parking', 'toll', 'other')),
  offense_at timestamptz not null,
  received_on date not null,
  reference text,
  description text,
  amount double precision not null check (amount > 0),
  currency text not null default 'RON' check (currency in ('RON', 'EUR')),
  discount_until date,
  paid_on date,
  paid_amount double precision check (paid_amount >= 0),
  driver_named_on date,
  charge_driver boolean not null default true,
  settlement_id bigint references public.weekly_settlements (id) on delete set null,
  attachment_path text,
  attachment_name text,
  attachment_type text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fines_paid_check check ((paid_on is null) = (paid_amount is null))
);
create index fines_user_offense_idx on public.fines (user_id, offense_at desc);
create index fines_car_idx on public.fines (car_id);
create index fines_driver_idx on public.fines (driver_id) where driver_id is not null;
create index fines_settlement_idx on public.fines (settlement_id) where settlement_id is not null;
create trigger fines_set_updated_at
  before update on public.fines
  for each row execute function public.set_vehix_updated_at();
create trigger fines_validate_car_owner
  before insert or update of car_id, user_id on public.fines
  for each row execute function public.validate_vehix_car_owner();

create or replace function private.validate_fine_links()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.driver_id is not null and not exists (
    select 1 from public.drivers d where d.id = new.driver_id and d.user_id = new.user_id
  ) then
    raise exception 'Driver not found';
  end if;
  if new.settlement_id is not null and not exists (
    select 1 from public.weekly_settlements s where s.id = new.settlement_id and s.user_id = new.user_id and s.driver_id = new.driver_id
  ) then
    raise exception 'Settlement not found';
  end if;
  return new;
end;
$$;
create trigger fines_validate_links
  before insert or update of driver_id, settlement_id, user_id on public.fines
  for each row execute function private.validate_fine_links();
revoke all on all functions in schema private from public, anon, authenticated;

-- Fuel use per vehicle and driver in a period, next to the vehicle's own baseline
-- (the 12 weeks before the period, or all other weeks when that is too little data).
create or replace function public.fuel_consumption_by_driver(p_from date, p_to date)
returns table (car_id bigint, driver_id bigint, distance double precision, fuel_used double precision, consumption double precision, baseline double precision)
language sql
stable
set search_path = ''
as $$
  with period as (
    select t.car_id, coalesce(t.driver_id, public.driver_for_car_on(t.car_id, t.date)) as driver_id, t.distance, t.fuel_used
    from public.trips t
    where t.status = 'done' and t.date between p_from and p_to
  ),
  grouped as (
    select p.car_id, p.driver_id, sum(p.distance) as distance, sum(p.fuel_used) as fuel_used
    from period p group by p.car_id, p.driver_id
  ),
  history as (
    select t.car_id,
      sum(t.fuel_used) filter (where t.date >= p_from - 84 and t.date < p_from) as recent_fuel,
      sum(t.distance) filter (where t.date >= p_from - 84 and t.date < p_from) as recent_km,
      sum(t.fuel_used) filter (where t.date < p_from or t.date > p_to) as other_fuel,
      sum(t.distance) filter (where t.date < p_from or t.date > p_to) as other_km
    from public.trips t
    where t.status = 'done' and t.car_id in (select g.car_id from grouped g)
    group by t.car_id
  )
  select g.car_id, g.driver_id, g.distance, g.fuel_used,
    case when g.distance > 0 then g.fuel_used / g.distance * 100 end,
    case
      when h.recent_km >= 300 then h.recent_fuel / h.recent_km * 100
      when h.other_km >= 300 then h.other_fuel / h.other_km * 100
    end
  from grouped g
  left join history h on h.car_id = g.car_id
$$;
revoke all on function public.fuel_consumption_by_driver(date, date) from public, anon;
grant execute on function public.fuel_consumption_by_driver(date, date) to authenticated;

-- Row level security: every row belongs to its owner.
alter table public.driver_documents enable row level security;
alter table public.service_plans enable row level security;
alter table public.fines enable row level security;

create policy driver_documents_select_own on public.driver_documents for select to authenticated using ((select auth.uid()) = user_id);
create policy driver_documents_insert_own on public.driver_documents for insert to authenticated with check ((select auth.uid()) = user_id);
create policy driver_documents_update_own on public.driver_documents for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy driver_documents_delete_own on public.driver_documents for delete to authenticated using ((select auth.uid()) = user_id);

create policy service_plans_select_own on public.service_plans for select to authenticated using ((select auth.uid()) = user_id);
create policy service_plans_insert_own on public.service_plans for insert to authenticated with check ((select auth.uid()) = user_id);
create policy service_plans_update_own on public.service_plans for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy service_plans_delete_own on public.service_plans for delete to authenticated using ((select auth.uid()) = user_id);

create policy fines_select_own on public.fines for select to authenticated using ((select auth.uid()) = user_id);
create policy fines_insert_own on public.fines for insert to authenticated with check ((select auth.uid()) = user_id);
create policy fines_update_own on public.fines for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy fines_delete_own on public.fines for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.driver_documents, public.service_plans, public.fines from anon;
grant select, insert, update, delete on public.driver_documents, public.service_plans, public.fines to authenticated;
grant usage, select on sequence public.driver_documents_id_seq to authenticated;
grant usage, select on sequence public.service_plans_id_seq to authenticated;
grant usage, select on sequence public.fines_id_seq to authenticated;
